language: python
python:
 # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install pylint
# command to run tests
script:
  - pylint main.py